import { useState } from "react";
import { Link } from "react-router-dom";
import api from "../api";
import "./LoginPage.css";

function LoginPage({ onLogin }) {
  const [form, setForm] = useState({ email: "", password: "" });
  const [error, setError] = useState("");

  const change = (e) =>
    setForm({ ...form, [e.target.name]: e.target.value });

  const submit = async (e) => {
    e.preventDefault();
    setError("");
    try {
      const res = await api.post("/auth/signin", form);
      onLogin(res.data);
    } catch (err) {
      setError(err.response?.data?.message || "Login failed");
    }
  };

  return (
    <div className="login-root">
      <div className="login-card">
        <h1 className="login-title">HRMS Login</h1>
        <p className="login-subtitle">
          Use the credentials generated by HR or the account you just created.
        </p>

        {error && <p className="login-error">{error}</p>}

        <form className="login-form" onSubmit={submit}>
          <div className="login-group">
            <label>Email</label>
            <input
              name="email"
              type="email"
              value={form.email}
              onChange={change}
              placeholder="employee@company.com"
              required
            />
          </div>
          <div className="login-group">
            <label>Password</label>
            <input
              name="password"
              type="password"
              value={form.password}
              onChange={change}
              placeholder="••••••••"
              required
            />
          </div>
          <button type="submit" className="login-button">
            Sign In
          </button>
        </form>

        <p className="login-footer">
          No account?{" "}
          <Link to="/register" className="login-link">
            Sign Up
          </Link>
        </p>
      </div>
    </div>
  );
}

export default LoginPage;
